/* tslint:disable */
/* eslint-disable */
/**
 * Konfig\'s REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GenerateRequestBody } from '../models';
// @ts-ignore
import { GenerateResponseBody } from '../models';
import { paginate } from "../pagination/paginate";
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * SdkApi - axios parameter creator
 * @export
 */
export const SdkApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Generate SDKs
         * @summary Generate SDKs and receive signed S3 download URLs for the generated packages.
         * @param {GenerateRequestBody} [generateRequestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generate: async (generateRequestBody?: GenerateRequestBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/generate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(generateRequestBody, localVarRequestOptions, configuration)

            requestBeforeHook({
              queryParameters: localVarQueryParameter,
              requestConfig: localVarRequestOptions,
              path: localVarPath,
              configuration
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SdkApi - functional programming interface
 * @export
 */
export const SdkApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SdkApiAxiosParamCreator(configuration)
    return {
        /**
         * Generate SDKs
         * @summary Generate SDKs and receive signed S3 download URLs for the generated packages.
         * @param {SdkApiGenerateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generate(requestParameters: SdkApiGenerateRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenerateResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generate(requestParameters, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SdkApi - factory interface
 * @export
 */
export const SdkApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SdkApiFp(configuration)
    return {
        /**
         * Generate SDKs
         * @summary Generate SDKs and receive signed S3 download URLs for the generated packages.
         * @param {SdkApiGenerateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generate(requestParameters: SdkApiGenerateRequest = {}, options?: AxiosRequestConfig): AxiosPromise<GenerateResponseBody> {
            return localVarFp.generate(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for generate operation in SdkApi.
 * @export
 * @interface SdkApiGenerateRequest
 */
export type SdkApiGenerateRequest = {
    
} & GenerateRequestBody

/**
 * SdkApi - object-oriented interface
 * @export
 * @class SdkApi
 * @extends {BaseAPI}
 */
export class SdkApi extends BaseAPI {
    /**
     * Generate SDKs
     * @summary Generate SDKs and receive signed S3 download URLs for the generated packages.
     * @param {SdkApiGenerateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SdkApi
     */
    public generate(requestParameters: SdkApiGenerateRequest = {}, options?: AxiosRequestConfig) {
        return SdkApiFp(this.configuration).generate(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
