/* tslint:disable */
/* eslint-disable */
/**
 * Konfig\'s REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyFixConfigModifyValue } from './generate-request-body-fix-config-modify-value';

/**
 * 
 * @export
 * @interface GenerateRequestBodyFixConfig
 */
export interface GenerateRequestBodyFixConfig {
    /**
     * 
     * @type {{ [key: string]: GenerateRequestBodyFixConfigModifyValue; }}
     * @memberof GenerateRequestBodyFixConfig
     */
    'modify'?: { [key: string]: GenerateRequestBodyFixConfigModifyValue; };
}

