/* tslint:disable */
/* eslint-disable */
/**
 * Konfig\'s REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsAndroidFilesValue } from './generate-request-body-generators-android-files-value';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsAndroidGit } from './generate-request-body-generators-android-git';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsAndroidTest } from './generate-request-body-generators-android-test';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsTypescriptAnyOfPagination } from './generate-request-body-generators-typescript-any-of-pagination';

/**
 * 
 * @export
 * @interface GenerateRequestBodyGeneratorsTypescriptAnyOf
 */
export interface GenerateRequestBodyGeneratorsTypescriptAnyOf {
    /**
     * 
     * @type {{ [key: string]: GenerateRequestBodyGeneratorsAndroidFilesValue; }}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'files'?: { [key: string]: GenerateRequestBodyGeneratorsAndroidFilesValue; };
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'version': string;
    /**
     * 
     * @type {GenerateRequestBodyGeneratorsAndroidGit}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'git': GenerateRequestBodyGeneratorsAndroidGit;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'outputDirectory': string;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'readmeSnippet'?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'apiDocumentationAuthenticationPartial'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'disabled'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'defaultTimeout'?: number;
    /**
     * 
     * @type {GenerateRequestBodyGeneratorsAndroidTest}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'test'?: GenerateRequestBodyGeneratorsAndroidTest;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'clientName': string;
    /**
     * acme-typescript-sdk
     * @type {any}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'npmName': any;
    /**
     * 
     * @type {GenerateRequestBodyGeneratorsTypescriptAnyOfPagination}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'pagination'?: GenerateRequestBodyGeneratorsTypescriptAnyOfPagination;
    /**
     * 
     * @type {Array<string>}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'clientState'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof GenerateRequestBodyGeneratorsTypescriptAnyOf
     */
    'topLevelOperations'?: { [key: string]: string; };
}

