/* tslint:disable */
/* eslint-disable */
/**
 * Konfig REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyAdditionalGeneratorsValueAnyOfFilesValue } from './generate-request-body-additional-generators-value-any-of-files-value';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsAndroidGit } from './generate-request-body-generators-android-git';
// May contain unused imports in some cases
// @ts-ignore
import { GenerateRequestBodyGeneratorsAndroidTest } from './generate-request-body-generators-android-test';

/**
 * 
 * @export
 * @interface GenerateRequestBodyAdditionalGeneratorsValueAnyOf
 */
export interface GenerateRequestBodyAdditionalGeneratorsValueAnyOf {
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'generator': GenerateRequestBodyAdditionalGeneratorsValueAnyOfGeneratorEnum;
    /**
     * 
     * @type {{ [key: string]: GenerateRequestBodyAdditionalGeneratorsValueAnyOfFilesValue; }}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'files'?: { [key: string]: GenerateRequestBodyAdditionalGeneratorsValueAnyOfFilesValue; };
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'version': string;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'outputDirectory': string;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'readmeSnippet'?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'apiDocumentationAuthenticationPartial'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'disabled'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'defaultTimeout'?: number;
    /**
     * 
     * @type {GenerateRequestBodyGeneratorsAndroidTest}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'test'?: GenerateRequestBodyGeneratorsAndroidTest;
    /**
     * 
     * @type {GenerateRequestBodyGeneratorsAndroidGit}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'git': GenerateRequestBodyGeneratorsAndroidGit;
    /**
     * com.acme
     * @type {any}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'groupId': any;
    /**
     * acme
     * @type {any}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'packageName'?: any;
    /**
     * ascme-java-sdk
     * @type {any}
     * @memberof GenerateRequestBodyAdditionalGeneratorsValueAnyOf
     */
    'artifactId': any;
}

export const GenerateRequestBodyAdditionalGeneratorsValueAnyOfGeneratorEnum = {
    Java: 'java'
} as const;

export type GenerateRequestBodyAdditionalGeneratorsValueAnyOfGeneratorEnum = typeof GenerateRequestBodyAdditionalGeneratorsValueAnyOfGeneratorEnum[keyof typeof GenerateRequestBodyAdditionalGeneratorsValueAnyOfGeneratorEnum];


