/* tslint:disable */
/* eslint-disable */
/**
 * Konfig REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface LintResponseBody
 */
export interface LintResponseBody {
    /**
     * 
     * @type {Array<any>}
     * @memberof LintResponseBody
     */
    'diagnosis': Array<any>;
    /**
     * `true` if no warnings or errors were found while linting else `false`
     * @type {any}
     * @memberof LintResponseBody
     */
    'passed': any;
}

