/* tslint:disable */
/* eslint-disable */
/**
 * Konfig REST API
 * To help you generate SDKs with Konfig
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface PushRequestBodyGitHub
 */
export interface PushRequestBodyGitHub {
    /**
     * The account owner of the repository
     * @type {any}
     * @memberof PushRequestBodyGitHub
     */
    'owner': any;
    /**
     * The name of the repository
     * @type {any}
     * @memberof PushRequestBodyGitHub
     */
    'repo': any;
}

